const categorrender =[
    {
      name: 'Burger',
      image: require('../assets/rendergatergor/images/burger/br3.png'),
      items: [
        {
          name: 'Classic Burger',
          weight: 120,
          rating: '5.0',
          price: 199,
          isTopOfTheWeek: true,
          image: require('../assets/rendergatergor/images/burger/br3.png'),
          size: 'Large 8"',
          crust: 'Thick Crust',
          delivery: 25,
          ingredients: [
            require('../assets/rendergatergor/images/flour.png'),
            require('../assets/rendergatergor/images/Tomato.png'),
            require('../assets/rendergatergor/images/Sliced-Onion.png'),
            require('../assets/rendergatergor/images/cheese.png'),
          ],
        },
        {
          name: 'Aloo Tikki Burger',
          weight: 150,
          rating: '4.5',
          price: 99,
          isTopOfTheWeek: false,
          image: require('../assets/rendergatergor/images/burger/br2.png'),
          size: 'Large 12"',
          crust: 'Thick Crust',
          delivery: 20,
          ingredients: [
            require('../assets/rendergatergor/images/flour.png'),
            require('../assets/rendergatergor/images/Tomato.png'),
            require('../assets/rendergatergor/images/Sliced-Onion.png'),
            require('../assets/rendergatergor/images/cheese.png'),
          ],
        },
        {
          name: 'Biggie Cheese',
          weight: 250,
          rating: '4.2',
          price: 299,
          isTopOfTheWeek: false,
          image: require('../assets/rendergatergor/images/burger/br1.png'),
          size: 'Large 10"',
          crust: 'Thick Crust',
          delivery: 35,
          ingredients: [
            require('../assets/rendergatergor/images/flour.png'),
            require('../assets/rendergatergor/images/Tomato.png'),
            require('../assets/rendergatergor/images/Sliced-Onion.png'),
            require('../assets/rendergatergor/images/cheese.png'),
          ],
        },
      ],
    },
      {
          name: 'Pizza',
          image: require('../assets/rendergatergor/images/piza/bz1.png'),
          items: [
            {
              name: 'Pepperoni Pizza',
              weight: 250,
              rating: '5.0',
              price: 199,
              isTopOfTheWeek: true,
              image: require('../assets/rendergatergor/images/piza/bz1.png'),
              size: 'Large 14"',
              crust: 'Thin Crust',
              delivery: 30,
              ingredients: [
                require('../assets/rendergatergor/images/flour.png'),
                require('../assets/rendergatergor/images/Tomato.png'),
                require('../assets/rendergatergor/images/Sliced-Onion.png'),
                require('../assets/rendergatergor/images/cheese.png'),
              ],
            },
            {
              name: 'Plain Cheese Pizza',
              weight: 300,
              rating: '4.5',
              price: 299,
              isTopOfTheWeek: false,
              image: require('../assets/rendergatergor/images/piza/bz2.png'),
              size: 'Large 16"',
              crust: 'Thin Cheese',
              delivery: 25,
              ingredients: [
                require('../assets/rendergatergor/images/flour.png'),
                require('../assets/rendergatergor/images/Tomato.png'),
                require('../assets/rendergatergor/images/Sliced-Onion.png'),
                require('../assets/rendergatergor/images/cheese.png'),
              ],
            },
            {
              name: 'Mexican Green Wave',
              weight: 350,
              rating: '4.2',
              price: 499,
              isTopOfTheWeek: false,
              image: require('../assets/rendergatergor/images/piza/bz3.png'),
              size: 'Large 15"',
              crust: 'Thin Crust',
              delivery: 45,
              ingredients: [
                require('../assets/rendergatergor/images/flour.png'),
                require('../assets/rendergatergor/images/Tomato.png'),
                require('../assets/rendergatergor/images/Sliced-Onion.png'),
                require('../assets/rendergatergor/images/cheese.png'),
              ],
            },
          ],
      },
      {
          
          name: 'Soft Drinks',
          image: require('../assets/rendergatergor/images/soft jose/cola.png'),
          items: [
              {
                  name: 'Coco Cola',
                  weight: 200,
                  rating: '5.0',
                  price: 299,
                  isTopOfTheWeek: true,
                  image: require('../assets/rendergatergor/images/soft jose/cola.png'),
                  size: 'Medium Glass',
                  crust: 'Small Ice',
                  delivery: 10,
                  ingredients: [require('../assets/rendergatergor/images/soft jose/cola.png')],
              },
              {
                  name: 'Orange Juice',
                  weight: 500,
                  rating: '4.5',
                  price: 199,
                  isTopOfTheWeek: false,
                  image: require('../assets/rendergatergor/images/soft jose/orange.png'),
                  size: 'LArge Glass',
                  crust: 'Large Ice',
                  delivery: 8,
                  ingredients: [require('../assets/rendergatergor/images/soft jose/orange.png')],
              },
              {
                  name: 'Mango Juice',
                  weight: 150,
                  rating: '4.2',
                  price: 99,
                  isTopOfTheWeek: false,
                  image: require('../assets/rendergatergor/images/soft jose/mango.png'),
                  size: 'Large Glass',
                  crust: 'Small Ice',
                  delivery: 5,
                  ingredients: [require('../assets/rendergatergor/images/soft jose/mango.png')],
              },
  
          ],
      },    
  
  ]
  export default categorrender;